# write a python program to show such type of layout of Number , Square , and Cube =>
print("NUMBER\t\tSQUARE_OF_NUMBER\tCUBE_OF_NUMBER")
# print("1"+"\t\t"+str(1 * 1)+"\t\t\t\t"+str(1 * 1 * 1))
# print("1"+"\t\t"+str(pow(1 , 2))+"\t\t\t"+str(pow(1 , 3)))
print("1"+"\t\t"+str(1 ** 2)+"\t\t\t"+str(1 ** 3))
# print("2"+"\t\t"+str(2 * 2)+"\t\t\t\t"+str(2 * 2 * 2))
# print("2"+"\t\t"+str(pow(2 , 2))+"\t\t\t"+str(pow(2 , 3)))
print("2"+"\t\t"+str(2 ** 2)+"\t\t\t"+str(2 ** 3))
# print("3"+"\t\t"+str(3 * 3)+"\t\t\t\t"+str(3 * 3 * 3))
# print("3"+"\t\t"+str(pow(3 , 2))+"\t\t\t"+str(pow(3 , 3)))
print("3"+"\t\t"+str(3 ** 2)+"\t\t\t"+str(3 ** 3))
# print("4"+"\t\t"+str(4 * 4)+"\t\t\t\t"+str(4 * 4 * 4))
# print("4"+"\t\t"+str(pow(4 , 2))+"\t\t\t"+str(pow(4 , 3)))
print("4"+"\t\t"+str(4 ** 2)+"\t\t\t"+str(4 ** 3))
# print("5"+"\t\t"+str(5 * 5)+"\t\t\t\t"+str(5 * 5 * 5))
# print("5"+"\t\t"+str(pow(5 , 2))+"\t\t\t"+str(pow(5 , 3)))
print("5"+"\t\t"+str(5 ** 2)+"\t\t\t"+str(5 ** 3))