# write a python program to perform all arthimetic operations on three variables =>
# frist_num = float(input("please enter the frist number is = "))
# second_num = float(input("please enter the second number is = "))
# third_num = float(input("please enter the third number is = "))
# print("\n")
# print("the values of the two numbers is : \n")
# print("the value of the frist number is = "+str(frist_num))
# print("the value of the second number is = "+str(second_num))
# print("the value of the third number is = "+str(third_num))
# print("the arthimetic operations into the two values of the two numbers is : \n")
# print("the result of the addition arthimetic operation of the three numbers is = "+str(frist_num + second_num + third_num))
# print("the result of the subtraction arthimetic operation of the three numbers is = "+str(frist_num - second_num - third_num))
# print("the reuslt of the multiplication arthimetic operation of the three numbers is = "+str(frist_num * second_num * third_num))
# print("the result of the division arthimetic operation of the numbers is = "+str(frist_num / second_num / third_num))
# print("the result of the modulus arthimetic operation of the three numbers is "+str(frist_num % second_num % third_num))

frist_number = float(input("please enter the frist number is = "))
second_number = float(input("please enter the second number is = "))
third_number = float(input("please enter the third number is = "))
def get_all_arthimetic_operations_into_three_numbers(frist_num , second_num , third_num) :
    print("\n")
    print("the value of the frist number is = "+str(frist_num))
    print("the value of the second number is = "+str(second_num))
    print("the value of the third number is = "+str(third_num))
    print("the arthimetic operations into the three values of the three numbers is : \n")
    print("the result of the addition arthimetic operation of the three numbers is = "+str(frist_num + second_num + third_num))
    print("the result of the subtraction arthimetic operation of the three numbers is = "+str(frist_num - second_num - third_num))
    print("the result of the multiplication arthimetic operation of the three numbers is = "+str(frist_num * second_num * third_num))
    print("the result of the division arthimetic operation of the three numbers is = "+str(frist_num / second_num / third_num))
    print("the result of the modulus arthimetic operation of the three numbers is = "+str(frist_num % second_num % third_num))
get_all_arthimetic_operations_into_three_numbers(frist_number , second_number , third_number )